version: "3.9"

services:
  app:
    build: .
    container_name: myapp
    restart: always

    environment:
      - ENV=PROD
      - PRIVATE_KEY_PATH=/run/secrets/privatekey.pem
      - CERT_PATH=/run/secrets/server.crt

    volumes:
      - /opt/myapp/secrets/privatekey.pem:/run/secrets/privatekey.pem:ro
      - /opt/myapp/secrets/server.crt:/run/secrets/server.crt:ro

    ports:
      - "80:3000"
      - "443:8443"